version: 2
models:
  - name: mart_monthly_labour_metrics
    columns:
      - name: date_parsed
        tests:
          - not_null
      - name: geo
        tests:
          - not_null
      - name: year
        tests:
          - not_null
      - name: vacancies_per_1000
        tests:
          - dbt_utils.accepted_range:
                arguments:
                min_value: 0
                inclusive: true

      - name: total_job_vacancies
        tests:
          - dbt_utils.accepted_range:
                arguments:
                min_value: 0
                inclusive: true
  # mom_change_pct intentionally nullable — null for first 4 month per province
  # yoy_change_pct intentionally nullable — null for first 12 months per province
