version: 2

models:
  - name: stg_monthly_vacancies
    columns:
      - name: date_parsed
        tests:
          - not_null
      - name: geo
        tests:
          - not_null
      - name: year
        tests:
          - not_null

      - name: job_vacancies
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true


      - name: job_vacancy_rate
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true

      - name: payroll_employees
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true
      
      - name: total_employment
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true

  - name: stg_quarterly_vacancies
    columns:
      - name: date_parsed
        tests:
          - not_null
      - name: geo
        tests:
          - not_null
      - name: naics
        tests:
          - not_null
      - name: year
        tests:
          - not_null

      - name: job_vacancies
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true

      - name: job_vacancy_rate
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true

      - name: avg_offered_hourly_wage
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true

      - name: payroll_employees
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true
      
      - name: total_employment
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true

  - name: stg_naics_employed
    columns:
      - name: date_parsed
        tests:
          - not_null
      - name: geo
        tests:
          - not_null
      - name: naics
        tests:
          - not_null
      - name: year
        tests:
          - not_null
      - name: total_employment
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true